### ISSUE TITLE
Installing on Windows7

### ISSUE THREAD

**Issue by spicoflorin** [DonDebonair/virtual-hadoop-cluster#3]
Hello!
  I have installed VirtualBox and Vagrant on my Windows 7 machine. I have ran your vagrant configuration file, but I'm getting the following error:
vm:
- The '' provisioner could not be found.
  Vagrant:
- Unknown configuration section 'hostmanager'.
  Can you please tell me how to solve this issue?
  Thanks.

**Comment by DonDebonair** [comment]
You have to install the _hostmanager_ plugin:

```
$ vagrant plugin install vagrant-hostmanager
```
