### ISSUE TITLE
Need DNS

### ISSUE THREAD

**Issue by ulise** [DonDebonair/virtual-hadoop-cluster#4]
I got DNS issues running this on a Windows (10) box. The installation of the slaves was broken, because they couldn't resolve the hostname of the master (host 10.211.55.100) didn't work.

Installing a dnsmasq on the master and setting up the slaves to use it solved this.
I'll create a pull request on this.
Cheers,
Uli

**Comment by DonDebonair** [comment]
That is strange. Vagrant should set the correct hostnames, so the VMs should be able to find each other without using `dnsmasq`. For an example how these scripts should be used: http://dandydev.net/blog/installing-virtual-hadoop-cluster

**Comment by ulise** [comment]
Yes, Vagrant sets the hostnames, but that´s not enough for resolving them via "host xxx". Could be that on some hosts the hostnames are resolved from the hosts hostnmames :-)
Not so with Windows. For example ping vm-cluster-node3 works, but host vm-cluster-node3 does not. I exacly followed your description.
Cheers,
Uli
